### ISSUE TITLE
retrieve_in_progress_spectator_game_info

### ISSUE THREAD

**Issue by mmlo** [EloGank/lol-php-api#9]
I'm having problems with timeout to get retrieve_in_progress_spectator_game_info information.

Region: NA, BR.

EloGankAPI.DEBUG: Client sent: {"region":"NA","route":"game.retrieve_in_progress_spectator_game_info","parameters":["league"]} [] []
EloGankAPI.ERROR: Client [127.0.0.1]: Request timed out, the client will reconnect [] []
EloGankAPI.DEBUG: Reconnect process has been requested, kill the old process and create a new one [] []
EloGankAPI.DEBUG: Client async #2 (NA) (pid: #15716) has been killed [] []

what can it be?

**Comment by RanadeepPolavarapu** [comment]
https://developer.riotgames.com/discussion/riot-games-api/show/TdslWt3W

**Comment by mmlo** [comment]
what needs to be done to prevent this disconnect when it returns null?

**Comment by Divi** [comment]
This update is pretty bad, because I use the previous exception to know if a player exists in the Riot database and prevent a timeout exception because of the `NULL` response body for the route `summoner.summoner_by_name`.

I'll check how I can fix this issue, but I think I will have to delete the anti-overload system for these two routes.

**Comment by Divi** [comment]
@mmlo @RanadeepPolavarapu the `master` branch has been updated with the fix : https://github.com/EloGank/lol-php-api/commit/8c8b8650642cb9acf99641d9a52803219552d499

**Note :** the `summoner.summoner_existence`, `summoner.summoner_by_name` and `game.retrieve_in_progress_spectator_game_info` routes can now return a `NULL` response body instead of an error. **Please update your application code.**
If you used `composer` to install the API, update your `composer.json` : `"elogank/php-lol-api": "1.2.*@dev"`

You can always use the previous version by switching to the `1.1` tag [here](https://github.com/EloGank/lol-php-api/tree/1.1).

Thanks for the quick report :+1:

**Comment by RanadeepPolavarapu** [comment]
:+1 Thanks @Divi.

**Comment by mmlo** [comment]
awesome @Divi, thanks!
